### ISSUE TITLE
when it will support MAUI .net 8 

### ISSUE THREAD

**Issue by omernaser** [newrelic/newrelic-maui-plugin#38]
i can't use it in my Maui project because of that any idea when it is supported can I have any release date for .net 8 and if there is any beta or workaround please let me know

**Comment by ndesai-newrelic** [comment]
@omernaser we will add support for it and release it by EOW.

**Comment by sgreifeneder** [comment]
We are also using it in a .NET 8 Maui App. I can see some analytics coming in, as well as crash reports for Android (but not for iOS, though). 
@omernaser what exactly doesn't work for you? 
@ndesai-newrelic looking forward to the new version!

**Comment by ndesai-newrelic** [comment]
@omernaser what errors are you getting?

**Comment by ndesai-newrelic** [comment]
@omernaser added support for net 8.0 in release 1.1.1. 

https://www.nuget.org/packages/NewRelic.MAUI.Plugin/1.1.1

**Comment by omernaser** [comment]
@ndesai-newrelic  the issue still exists the nuget can't be installed yet   iam using visual studio Version 17.12.0 and my 		<TargetFrameworks>net8.0-ios;net8.0-android34.0</TargetFrameworks>



 System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\OIHmaid\.nuget\packages\newrelic.maui.ios.binding\7.5.3.1\lib\net8.0-ios18.0\NewRelic.MAUI.iOS.Binding.resources\NewRelic.xcframework\ios-arm64_x86_64-simulator\NewRelic.framework\Modules\NewRelic.swiftmodule\arm64-apple-ios-simulator.private.swiftinterface'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.Create(String path)
   at NuGet.Packaging.StreamExtensions.Testable.MmapCopy(Stream inputStream, String fileFullPath, Int64 size)
   at NuGet.Packaging.StreamExtensions.Testable.CopyToFile(Stream inputStream, String fileFullPath)
   at NuGet.Packaging.PackageFileExtractor.ExtractPackageFile(String source, String target, Stream stream)
   at NuGet.Packaging.PackageArchiveReader.CopyFiles(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken token)
   at NuGet.Packaging.PackageReaderBase.CopyFilesAsync(String destination, IEnumerable`1 packageFiles, ExtractPackageFileDelegate extractFile, ILogger logger, CancellationToken cancellationToken)
   at NuGet.Packaging.PackageExtractor.<>c__DisplayClass5_0.<<InstallFromSourceAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.Common.ConcurrencyUtilities.<ExecuteWithFileLockedAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
